### ISSUE TITLE
On page Refresh URL Not Works

### ISSUE THREAD

**Issue by mukeshbadgujar** [GeekLaunch/pushstate-and-popstate#1]
One Problem in your code, i download from your git and run it, now see, when i click any of div and if i refresh the page, then  url not works, gives Error : The requested URL /pushstate-and-popstate-master/selected=box-2 was not found on this server.

Plzz tell me how to solve it...

**Comment by encody** [comment]
This is intended behavior as shown in the video (i.e. you can change the url without actually having the browser request the page from the server). If you'd like to load a state based on the requested path, you have a few options:

1. Write some server-side code that does that
2. Only change the hash (the part of the url after the #). The hash is not sent to the server
3. Only change the query string (the part of the url after the ?). The query string IS sent to the server.
